services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - '18888:18888'
      - '18889:18889'
    volumes:
      - type: bind
        source: ./aspire-dashboard-config.json
        target: /app/config_files/aspire-dashboard-config.json
        read_only: true
    environment:
      - DOTNET_DASHBOARD_CONFIG_FILE_PATH=config_files/aspire-dashboard-config.json
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    volumes:
      - type: bind
        source: ./azurite
        target: /data
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
  postgres:
    image: postgres:17.6
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=Pl3@s3UseASt0ngP@ssw0rdN0tL!k3Th!s0n3
      - POSTGRES_DB=binacle_net
    
