@Email = useremail@domain.com
@Password = userspassword

POST https://{{HOST}}/api/users
Accept: application/json
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}
