domains:
  - domain: docs.binacle.net
    type: PRIMARY
ingress:
  rules:
    - component:
        name: binacle-net-docs
      match:
        path:
          prefix: /
name: binacle-net-docs
region: fra
static_sites:
  - environment_slug: html
    github:
      branch: main
      repo: ChrisMavrommatis/Binacle.Net
    name: binacle-net-docs
    source_dir: docs
