// Service Module requests

### Variables

##

### Healthcheck
GET https://{{HOST}}/_health
Accept: application/json



### Auth Token
POST https://{{HOST}}/auth/token
Accept: application/json
Content-Type: application/json

{
	"email": "test@test.com",
	"password" : "testpassword"
}

