<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Config_Files\**\*.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="xunit.runner.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
		<PackageReference Include="Shouldly" />
		<PackageReference Include="xunit.v3.mtp-v2" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
		<Using Include="Shouldly" />
		<Using Include="FluxResults" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Binacle.Net.ServiceModule\Binacle.Net.ServiceModule.csproj" />
		<ProjectReference Include="..\..\src\Binacle.Net\Binacle.Net.csproj" />
	</ItemGroup>

</Project>
