@id = 019678a2-ba63-7d29-8300-6ecdad1d6a63

PUT https://{{HOST}}/api/admin/account/{{id}}/subscription/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{BEARERTOKEN}}

{
  "type":"Normal",
  "status": "Active"
}
