<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<InternalsVisibleTo Include="$(ProjectName).UnitTests" />
		<InternalsVisibleTo Include="$(ProjectName).Benchmarks" />
		<InternalsVisibleTo Include="$(ProjectName).PerformanceTests" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\shared\src\Binacle.Packing\Binacle.Packing.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Using Include="Binacle.Geometry" />
	  <Using Include="Binacle.Packing" />
	  <Using Include="Binacle.Lib.Models" />
	</ItemGroup>

</Project>
