GET https://{{HOST}}/api/admin/accounts?page=1&pageSize=50
Accept: application/json
Authorization: Bearer {{BEARERTOKEN}}

###

GET https://{{HOST}}/api/admin/accounts?page=1&pageSize=50&allowDeleted=true
Accept: application/json
Authorization: Bearer {{BEARERTOKEN}}
