<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <IsPackable>false</IsPackable>

  </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Algorithms\Data\**\*.json" />
        <EmbeddedResource Include="ResultSelection\Data\**\*.json" />
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\..\lib\src\Binacle.Lib.Abstractions\Binacle.Lib.Abstractions.csproj" />
        <ProjectReference Include="..\Binacle.CompactNotation\Binacle.CompactNotation.csproj" />
    </ItemGroup>

</Project>
