<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Binacle.ViPaq\Binacle.ViPaq.csproj" />
		<ProjectReference Include="..\..\..\shared\Binacle.CompactNotation\Binacle.CompactNotation.csproj" />
	</ItemGroup>

</Project>
