
POST https://{{HOST}}/api/admin/account/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{BEARERTOKEN}}

{
  "username": "user@binacle.net",
  "email" : "user@binacle.net",
  "password": "userspassword"
}
