@ID = 019678a2-ba63-7d29-8300-6ecdad1d6a63

PATCH https://{{HOST}}/api/admin/account/{{ID}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{BEARERTOKEN}}

{
  "Username" : "user@binacle.net",
  "Email" : "user@binacle.net",
  "Password" : "userspassword",
  "Status": "Active",
  "Role": "User"
}

