@ID = 01966472-c08e-77b5-88a0-c8376ab48f15

PUT https://{{HOST}}/api/admin/account/{{ID}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{BEARERTOKEN}}

{
  "Username" : "user@binacle.net",
  "Email" : "user@binacle.net",
  "Password" : "userspassword",
  "Status": "Active",
  "Role": "User"
}

