# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Release Docker Image

on:
  release:
    types: [ "published" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Release Tag
      run: echo "Runing release for ${{ github.ref_name }}"
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DONET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore --runtime linux-x64
    - name: Publish
      run: dotnet publish ${{ vars.API_PROJECT_PATH }} -c Release -o ${{ vars.BUILD_OUTPUT }} --no-restore --self-contained --runtime linux-x64
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ vars.DOCKERHUB_ORGNAME }}/${{ vars.DOCKERHUB_REPO }}
        tags: |
          type=semver,pattern={{version}}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ vars.BUILD_DOCKERFILE }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      
